version: '2.3'
services:

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - "8081:8080"
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
    depends_on:
      - kafka

  zookeeper:
    hostname: zookeeper
    image: wurstmeister/zookeeper:3.4.6
    expose:
    - "2181"
    ports:
    - "2181:2181"
  
  kafka:
    image: wurstmeister/kafka
    env_file:
    - kafka/kafka-variables.env
    depends_on:
    - zookeeper
    ports:
    - '9092:9092'
    - '8082:8082'
    - '8083:8083'

  consumer-logger:
    build:
      context: consumer-logger
    environment:
      kafkaURL: kafka:9092
      topic: topic1
      GroupID: logger-group
    depends_on: 
    - kafka
    restart: always
  
  # consumer-logger2:
  #   build:
  #     context: consumer-logger
  #   environment:
  #     kafkaURL: kafka:9092
  #     topic: topic1
  #     GroupID: logger-group
  #   depends_on: 
  #   - kafka
  #   restart: always


  producer-random:
    build:
      context: producer-random
    environment:
      kafkaURL: kafka:9092
      topic: topic1
    depends_on: 
    - kafka
  
  producer-api:
    build:
      context: producer-api
    environment:
      kafkaURL: kafka:9092
      topic: topic1
    expose:
    - "8080"
    ports:
    - "8080:8080"
    depends_on: 
    - kafka
  
  # SARAMA APPS
  producer-sarama:
    build:
      context: producer-sarama
    expose:
    - "8080"
    ports:
    - "9090:8080"
    depends_on: 
    - kafka
    restart: always

  consumer-sarama1:
    build:
      context: consumer-sarama
    depends_on: 
    - kafka
    restart: always
  
  # consumer-sarama2:
  #   build:
  #     context: consumer-sarama
  #   depends_on: 
  #   - kafka
  #   restart: always

  # consumer-sarama3:
  #   build:
  #     context: consumer-sarama
  #   depends_on: 
  #   - kafka
  #   restart: always